create table if not exists customers (
  customer_id bigint primary key,
  full_name text not null,
  email text,
  city text,
  state text,
  customer_segment text,
  loyalty_tier text
);

create table if not exists orders (
  order_id bigint primary key,
  customer_id bigint not null references customers(customer_id) on delete restrict,
  order_datetime timestamptz not null,
  order_subtotal numeric(12, 2) not null,
  shipping_fee numeric(12, 2) not null,
  tax_amount numeric(12, 2) not null,
  order_total numeric(12, 2) not null,
  payment_method text,
  device_type text,
  ip_country text,
  promo_used boolean not null default false,
  promo_code text,
  risk_score numeric(6, 2) not null,
  is_fraud boolean not null default false
);

create table if not exists fraud_feedback (
  feedback_id bigint generated by default as identity primary key,
  order_id bigint not null unique references orders(order_id) on delete cascade,
  feedback_label text not null check (feedback_label in ('fraud', 'not_fraud')),
  review_notes text,
  reviewed_at timestamptz not null default now()
);

create index if not exists idx_orders_risk_datetime
  on orders (risk_score desc, order_datetime desc, order_id desc);

create index if not exists idx_orders_customer_id
  on orders (customer_id);

create index if not exists idx_fraud_feedback_order_id
  on fraud_feedback (order_id);